export const firebaseErrors = {
    'auth/email-already-exists': 'El correo electrónico ya está en uso',
    'auth/id-token-expired': 'El token de autenticación ha expirado',
    'auth/id-token-revoked': 'El token de autenticación ha sido revocado',
    'auth/internal-error': 'El servidor de autenticación ha fallado',
    'auth/invalid-email': 'El correo electrónico no es válido',
    'auth/user-not-found': 'No se encontró ninguna cuenta con este correo electrónico',
    'auth/wrong-password': 'Contraseña incorrecta',
    'auth/weak-password': 'La contraseña es demasiado débil',
    'auth/email-already-in-use': 'El correo electrónico ya está en uso por otra cuenta',
    'auth/operation-not-allowed': 'La operación no está permitida',
    'auth/too-many-requests': 'Demasiados intentos. Por favor, inténtalo más tarde',
    'auth/account-exists-with-different-credential': 'La cuenta ya existe con una credencial diferente',
    'auth/invalid-credential': 'Las credenciales no son válidas',
    'auth/invalid-verification-code': 'El código de verificación no es válido',
    'auth/invalid-verification-id': 'El ID de verificación no es válido',
    'auth/missing-verification-code': 'Falta el código de verificación',
    'auth/missing-verification-id': 'Falta el ID de verificación',
    'auth/requires-recent-login': 'Esta operación requiere un inicio de sesión reciente',
    'auth/user-disabled': 'La cuenta de usuario ha sido deshabilitada',
    'auth/user-token-expired': 'El token de usuario ha expirado',
    'auth/network-request-failed': 'Error de red. Por favor, verifica tu conexión',
    'auth/invalid-api-key': 'La clave API no es válida',
    'auth/app-not-authorized': 'La aplicación no está autorizada para usar Firebase Authentication',
    'auth/expired-action-code': 'El código de acción ha expirado',
    'auth/invalid-action-code': 'El código de acción no es válido',
    'auth/invalid-message-payload': 'El contenido del mensaje no es válido',
    'auth/invalid-recipient-email': 'El correo electrónico del destinatario no es válido',
    'auth/invalid-sender': 'El correo electrónico del remitente no es válido',
    'auth/missing-android-pkg-name': 'Falta el nombre del paquete de Android',
    'auth/missing-continue-uri': 'Falta la URI de continuación',
    'auth/missing-ios-bundle-id': 'Falta el ID del paquete de iOS',
    'auth/unauthorized-continue-uri': 'La URI de continuación no está autorizada',
    'auth/invalid-continue-uri': 'La URI de continuación no es válida',
    'auth/missing-phone-number': 'Falta el número de teléfono',
    'auth/invalid-phone-number': 'El número de teléfono no es válido',
    'auth/quota-exceeded': 'Se ha excedido la cuota de SMS',
    'auth/captcha-check-failed': 'La verificación del captcha ha fallado',
    'auth/cancelled-popup-request': 'La solicitud de ventana emergente ha sido cancelada',
    'auth/popup-blocked': 'La ventana emergente ha sido bloqueada por el navegador',
    'auth/popup-closed-by-user': 'La ventana emergente ha sido cerrada por el usuario',
    'auth/unauthorized-domain': 'El dominio no está autorizado para realizar esta operación',
};